# ls options
alias ll='ls -lh'
alias la='ls -Alh'
alias l='ls -CF'
alias lsd='ls -l | grep "^d"'
alias lless='ls -Al | less'

# bash editing/refreshing/viewing
alias sb='source ~/.bash_profile'
alias eb='vim ~/.bash_profile'
alias ev='vim ~/.vimrc'

# other stuff
alias mk='make -j8'
alias executable='chmod 755' 
alias cl='clear'
alias cpr="cp -r"
alias vimp='vim -p'

# grep
alias grep='grep --color'
alias grepr='grep -r --color'

# gcc
alias g++11="g++ --std=c++11"
alias g++14="g++ --std=c++14"

# show/hide hidden files in OSX
case $OSTYPE in darwin*)
    alias showfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    alias hidefiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
    alias brewuu='brew update && brew upgrade'
;; 
esac

# typos
alias cim='vim'
alias clera='clear'

# vagrant
alias vagrantgo='vagrant up && vagrant ssh'

# pip
alias pip2-update-all='pip2 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip install -U'
alias pip3-update-all='pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip install -U'
alias pip2-update='sudo -H pip2 install --upgrade pip'
alias pip3-update='sudo -H pip3 install --upgrade pip'

# tcl
alias tclsh='rlwrap tclsh'
