#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "$HOME/.common_profile.sh" ]]; then
  source "$HOME/.common_profile.sh"
fi

export PATH="$PATH:/usr/sbin"

fpath=(/usr/local/share/zsh-completions $fpath)
#rm -f ~/.zcompdump; compinit
#Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
# to load these completions, you may need to run this:
# chmod go-w '/usr/local/share'

PROMPT='%{$fg[green]%}%T '$PROMPT
clear

